### ISSUE TITLE
extend the filter keyword in _router.yaml to include lists?

### ISSUE THREAD

**Issue by wingillis** [jmarkow/dassort#1]
my experiments are usually named using just mouse ID's making it difficult to find a one-size-fits-all filter for my data. I could implement the filter to be a list to match any values within.

**Comment by wingillis** [comment]
I see that the filter is a regular expression - and @jmarkow told me pipes work just fine for listing multiple values, i.e. `1543|5143` for different mice

**Comment by jmarkow** [comment]
Yep we can use pipes for a standard `or` regex, though now lists for all parameters in `router.yaml` are now supported for multiple keys, config files, etc.  See #2 .
